version: '3'

services:
  limit-order-book:
    container_name: limit-order-book
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - my-datavolume:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    build:
      context: ./limit-book-order
      dockerfile: Dockerfile
    command: >
      sh -c "npm run dev"
    ports:
      - '8080:8080'
    depends_on:
      - limit-order-book
volumes:
  my-datavolume:
  cache:

