# Generated by Django 5.0.1 on 2024-01-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0003_rename_transactions_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy_order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='buy_transactions', to='limitOrderBookApp.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell_order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to='limitOrderBookApp.order'),
        ),
    ]
