# Generated by Django 5.0.1 on 2024-01-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0006_transaction_stock_name_alter_transaction_buy_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='limitOrderBookApp.stock'),
        ),
    ]
