# Generated by Django 5.0.1 on 2024-01-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0008_remove_transaction_stock_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stock_short_name',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_short_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='limitOrderBookApp.stock'),
        ),
    ]
