# Generated by Django 5.0.1 on 2024-01-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0011_transaction_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='limitOrderBookApp.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='limitOrderBookApp.order'),
        ),
    ]
