# Generated by Django 5.0.1 on 2024-01-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0012_remove_transaction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_order', to='limitOrderBookApp.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sell_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='limitOrderBookApp.order'),
        ),
    ]
