# Generated by Django 5.0.1 on 2024-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0013_order_order_status_alter_transaction_buy_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=5),
        ),
    ]
