# Generated by Django 5.0.1 on 2024-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrderBookApp', '0014_order_current_quantity_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='open', max_length=5),
        ),
    ]
